
package Vista;

import Controlador.Conexion;
import Datos.DatosClientes;
import Funciones.FuncionesClientes;
import Funciones.FuncionesFacturas;
import static Vista.Facturas.dchFechaInicio;
import Vista.Notificaciones.Aceptar_Cancelar;
import Vista.Notificaciones.Advertencia;
import Vista.Notificaciones.Fallo;
import Vista.Notificaciones.Realizado;
import java.awt.Color;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SwichBlade15
 */
public final class SeleccionarClientes extends javax.swing.JDialog {

    FuncionesClientes funcion = new FuncionesClientes();
    FuncionesFacturas funcionfacturas = new FuncionesFacturas();
    DatosClientes datos = new DatosClientes();
    private final Conexion mysql = new Conexion();
    private final Connection cn = Conexion.getConnection();
    private final String sSQL = "";
    int totalRegistros = 0;
    public DefaultTableModel modelo, modelo2;
    Date d;
    ResultSet rs;
    Statement st;
    PreparedStatement ps;
    String[] reg = new String[6];
    String where, buscarString, fechaInicio;
    int buscarInt;
    
    public SeleccionarClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        lblFondo.setBackground(null);

        mostrar("");
    }
    
    public void mostrar(String buscar) {
        try {
            funcion.seleccionarClientes(buscar);
            modelo = funcion.modelo;
            tblSeleccionarClientes.setModel(modelo);
            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void mostrar2(String buscar) {
        try {
            funcionfacturas.llenarDatos(funcionfacturas.codigo);
            modelo2 = funcionfacturas.modelo2;
            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void ocultar_columnas() {
        tblSeleccionarClientes.getColumnModel().getColumn(0).setMaxWidth(0);
        tblSeleccionarClientes.getColumnModel().getColumn(0).setMinWidth(0);
        tblSeleccionarClientes.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngSeleccionarClientes = new javax.swing.ButtonGroup();
        lblCerrar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        lblFondoBuscar = new javax.swing.JLabel();
        rbtnUsuario = new javax.swing.JRadioButton();
        rbtnNombre = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeleccionarClientes = new javax.swing.JTable();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar32.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 56, -1, -1));

        txtBuscar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 102, 255));
        txtBuscar.setText("Buscar Usuario...");
        txtBuscar.setBorder(null);
        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFocusLost(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 76, 140, 18));

        lblFondoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoBuscador.png"))); // NOI18N
        getContentPane().add(lblFondoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 170, 30));

        rbtnUsuario.setBackground(new java.awt.Color(255, 255, 255));
        rbtngSeleccionarClientes.add(rbtnUsuario);
        rbtnUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtnUsuario.setText("N° Usuario");
        rbtnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        rbtnNombre.setBackground(new java.awt.Color(255, 255, 255));
        rbtngSeleccionarClientes.add(rbtnNombre);
        rbtnNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtnNombre.setText("Nombre");
        rbtnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNombreActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        tblSeleccionarClientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tblSeleccionarClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSeleccionarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccionarClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSeleccionarClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 430, 260));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSeleccionarProductos.png"))); // NOI18N
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        Principal.lblProceso.setText("Proceso: OFF");
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void txtBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusGained
        if (txtBuscar.getText().equals("Buscar Usuario...")) {
            txtBuscar.setText("");
        }
    }//GEN-LAST:event_txtBuscarFocusGained

    private void txtBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusLost
        if (txtBuscar.getText().length() == 0) {
            txtBuscar.setText("Buscar Usuario...");
        }
    }//GEN-LAST:event_txtBuscarFocusLost

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        txtBuscar.transferFocus();
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        if (!rbtnUsuario.isSelected() && !rbtnNombre.isSelected()) {
            mensaje = "Seleccione primero lo que quiere buscar";
            advertencia();
            txtBuscar.setText("");
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }

        mostrar(txtBuscar.getText());
        
        int numerocaracteres = 29;
        if (txtBuscar.getText().length() > numerocaracteres) {
            evt.consume();
            mensaje = "Solo se permiten 30 caracteres";
            advertencia();
        }
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void tblSeleccionarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccionarClientesMouseClicked
        int seleccionar = tblSeleccionarClientes.rowAtPoint(evt.getPoint());
        if (evt.getClickCount() == 2) {
            Facturas.txtIdclientes.setText(String.valueOf(tblSeleccionarClientes.getValueAt(seleccionar, 0)));
            Facturas.txtNumeroUsuario.setText(String.valueOf(tblSeleccionarClientes.getValueAt(seleccionar, 1)));
            Facturas.txtClientes.setText(String.valueOf(tblSeleccionarClientes.getValueAt(seleccionar, 2) + " " + tblSeleccionarClientes.getValueAt(seleccionar, 3)));
            Facturas.txtDireccion.setText(String.valueOf(tblSeleccionarClientes.getValueAt(seleccionar, 4)));
            Facturas.txtInicioMedidor.setText(String.valueOf(tblSeleccionarClientes.getValueAt(seleccionar, 5)));

            funcionfacturas.datosClientes(Integer.parseInt(tblSeleccionarClientes.getValueAt(seleccionar, 0).toString()));

            if (funcionfacturas.codigo == 0) {

            } else {
                funcionfacturas.llenarDatos(funcionfacturas.codigo);

                //Convertir java.sql.date a java.util.date y mostrar en pantalla la Fecha Inicio
                SimpleDateFormat inicio = new SimpleDateFormat("yyyy-MM-dd");
                //Formato inicial.

                mostrar2("");

                try {
                    fechaInicio = String.valueOf(funcionfacturas.modelo2.getValueAt(0, 6));

                    d = inicio.parse(fechaInicio);
                } catch (ParseException e) {

                }

                //Aplica formato requerido.
                try {
                    inicio.applyPattern("dd/MM/yyyy");
                    String nuevoFormato = inicio.format(d);
                    Date fecha = inicio.parse(nuevoFormato);
                    dchFechaInicio.setDate(fecha);
                } catch (ParseException ex) {
                    Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
                }
                funcionfacturas.meses();
                funcionfacturas.vencimiento();
            }
            Facturas.txtCierreMedidor.setEditable(true);
            dispose();
        }
    }//GEN-LAST:event_tblSeleccionarClientesMouseClicked

    private void rbtnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnUsuarioActionPerformed
        txtBuscar.requestFocus();
    }//GEN-LAST:event_rbtnUsuarioActionPerformed

    private void rbtnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNombreActionPerformed
        txtBuscar.requestFocus();
    }//GEN-LAST:event_rbtnNombreActionPerformed

    Frame f = JOptionPane.getFrameForComponent(this);
    String encabezado;
    String mensaje;
    Icon icono;

    public void advertencia() {
        Advertencia dialog = new Advertencia(f, true);
        Advertencia.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void fallo() {
        Fallo dialog = new Fallo(f, true);
        Fallo.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void realizado() {
        Realizado dialog = new Realizado(f, true);
        Realizado.lblEncabezado.setText(mensaje);
        dialog.setVisible(true);
    }

    public void aceptarCancelar() {
        Aceptar_Cancelar dialog = new Aceptar_Cancelar(f, true);
        icono = new ImageIcon(getClass().getResource("/Imagenes/FondoCerrarSesion.png"));
        Aceptar_Cancelar.lblFondo.setIcon(icono);
        Aceptar_Cancelar.lblEncabezado.setText(encabezado);
        Aceptar_Cancelar.lblMensaje.setText(mensaje);
        dialog.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionarClientes dialog = new SeleccionarClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondoBuscar;
    public static javax.swing.JRadioButton rbtnNombre;
    public static javax.swing.JRadioButton rbtnUsuario;
    private javax.swing.ButtonGroup rbtngSeleccionarClientes;
    private javax.swing.JTable tblSeleccionarClientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
