package Vista;

import Controlador.Conexion;
import Datos.DatosClientes;
import Funciones.FuncionesClientes;
import Funciones.FuncionesFacturas;
import static Vista.Facturas.dchFechaInicio;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SwichBlade15
 */
public final class SeleccionarClientes extends javax.swing.JDialog {

    FuncionesClientes funcion = new FuncionesClientes();
    FuncionesFacturas funcionfacturas = new FuncionesFacturas();
    DatosClientes datos = new DatosClientes();
    private final Conexion mysql = new Conexion();
    private final Connection cn = Conexion.getConnection();
    private String sSQL = "";
    int totalRegistros = 0;
    public DefaultTableModel modelo;
    Date d;
    ResultSet rs;
    Statement st;
    PreparedStatement ps;
    String[] reg = new String[6];
    String where, buscarString;
    int buscarInt;

    public SeleccionarClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        mostrar("");
    }

    public void mostrar(String buscar) {
        try {
            funcion.seleccionarClientes(buscar);
            modelo = funcion.modelo;
            tblSeleccionarClientes.setModel(modelo);
            ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void ocultar_columnas() {
        tblSeleccionarClientes.getColumnModel().getColumn(0).setMaxWidth(0);
        tblSeleccionarClientes.getColumnModel().getColumn(0).setMinWidth(0);
        tblSeleccionarClientes.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngSeleccionar = new javax.swing.ButtonGroup();
        txtClientes = new javax.swing.JTextField();
        rbtnUsuario = new javax.swing.JRadioButton();
        rbtnNombre = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeleccionarClientes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rbtngSeleccionar.add(rbtnUsuario);
        rbtnUsuario.setText("N° Usuario");

        rbtngSeleccionar.add(rbtnNombre);
        rbtnNombre.setText("Nombre");

        tblSeleccionarClientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tblSeleccionarClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSeleccionarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeleccionarClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSeleccionarClientes);

        jButton1.setText("X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rbtnUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnNombre))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(txtClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnUsuario)
                    .addComponent(rbtnNombre))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSeleccionarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeleccionarClientesMouseClicked
        int seleccionar = tblSeleccionarClientes.rowAtPoint(evt.getPoint());
        if (evt.getClickCount() == 2) {
            Facturas.txtIdclientes.setText(String.valueOf(tblSeleccionarClientes.getValueAt(seleccionar, 0)));
            Facturas.txtNumeroUsuario.setText(String.valueOf(tblSeleccionarClientes.getValueAt(seleccionar, 1)));
            Facturas.txtClientes.setText(String.valueOf(tblSeleccionarClientes.getValueAt(seleccionar, 2) + " " + tblSeleccionarClientes.getValueAt(seleccionar, 3)));
            Facturas.txtDireccion.setText(String.valueOf(tblSeleccionarClientes.getValueAt(seleccionar, 4)));
            Facturas.txtInicioMedidor.setText(String.valueOf(tblSeleccionarClientes.getValueAt(seleccionar, 5)));

            funcionfacturas.datosClientes(Integer.parseInt(tblSeleccionarClientes.getValueAt(seleccionar, 0).toString()));
            funcionfacturas.llenarDatos(funcionfacturas.codigo);
            
            //Convertir java.sql.date a java.util.date y mostrar en pantalla la Fecha Inicio
            SimpleDateFormat inicio = new SimpleDateFormat("yyyy-MM-dd");
            //Formato inicial. 
            try {
                String fechaInicio = String.valueOf(funcionfacturas.modelo2.getValueAt(0, 6));
                d = inicio.parse(fechaInicio);
            } catch (ParseException e) {

            }

            //Aplica formato requerido.
            try {
                inicio.applyPattern("dd/MM/yyyy");
                String nuevoFormato = inicio.format(d);
                Date fecha = inicio.parse(nuevoFormato);
                dchFechaInicio.setDate(fecha);
            } catch (ParseException ex) {
                Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            funcionfacturas.meses();
            funcionfacturas.vencimiento();
           

            dispose();
        }
    }//GEN-LAST:event_tblSeleccionarClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeleccionarClientes dialog = new SeleccionarClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JRadioButton rbtnNombre;
    public static javax.swing.JRadioButton rbtnUsuario;
    private javax.swing.ButtonGroup rbtngSeleccionar;
    private javax.swing.JTable tblSeleccionarClientes;
    private javax.swing.JTextField txtClientes;
    // End of variables declaration//GEN-END:variables
}
